version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - './data:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
