version: '3'

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  front:
    image: nginx:latest
    container_name: 'front'
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.0.0.10

  api:
    extends:
      file: ./api/api.docker-compose.yml
      service: api
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.0.0.11
    depends_on:
      - db
      - mq

  db:
    extends:
      file: ./postgres/docker-compose.yml
      service: db
    networks:
      net:
        ipv4_address: 10.0.0.12

  db_gui:
    extends:
      file: ./postgres/docker-compose.yml
      service: adminer
    networks:
      net:
        ipv4_address: 10.0.0.13
    depends_on:
      - db

  rmq:
    extends:
      file: ./rabbitmq/docker-compose.yml
      service: rmq
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
    networks:
      net:
        ipv4_address: 10.0.0.14

  cache:
    redis:
      extends:
        file: ./redis/docker-compose.yml
        service: redis
    networks:
      net:
        ipv4_address: 10.0.0.15
